"""empty message

Revision ID: 206faf3c14f4
Revises: e1c9ef52d2c1
Create Date: 2023-02-14 21:30:34.393106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206faf3c14f4'
down_revision = 'e1c9ef52d2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha_model')
    # ### end Alembic commands ###
