"""empty message

Revision ID: 21be2cd55432
Revises: 1b4122f4bfcc
Create Date: 2023-02-14 23:52:13.857495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21be2cd55432'
down_revision = '1b4122f4bfcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminname', sa.String(length=100), nullable=False))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('adminsname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminsname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('adminname')

    # ### end Alembic commands ###
