"""empty message

Revision ID: 3046562eca12
Revises: 5b36acb1e04e
Create Date: 2023-02-22 20:34:50.110259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3046562eca12'
down_revision = '5b36acb1e04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier_information_model', schema=None) as batch_op:
        batch_op.alter_column('address_x',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('address_y',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier_information_model', schema=None) as batch_op:
        batch_op.alter_column('address_y',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('address_x',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
