"""empty message

Revision ID: 5b36acb1e04e
Revises: 0aafe9a47a01
Create Date: 2023-02-19 23:40:16.356974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b36acb1e04e'
down_revision = '0aafe9a47a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier_information_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_x', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('address_y', sa.Integer(), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier_information_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('address_y')
        batch_op.drop_column('address_x')

    # ### end Alembic commands ###
