"""empty message

Revision ID: 92e40f990dc7
Revises: b9dde8bbb99f
Create Date: 2023-02-27 00:13:20.667300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92e40f990dc7'
down_revision = 'b9dde8bbb99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_model', schema=None) as batch_op:
        batch_op.alter_column('adminname',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.drop_column('adminname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('username')

    with op.batch_alter_table('admin_model', schema=None) as batch_op:
        batch_op.alter_column('adminname',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
